export const Datasource = {
  '138b1b1ea66d41f9b6eacc6319418234': [
    {
      dbName: 'data_collect',
      tables: [
        {
          columns: [
            {
              fmt: null,
              foreignKeys: null,
              name: ['公共会计科目名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['是否现金或现金等价物'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_区划'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_批次'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['是否最底级科目'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['科目类别编号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助核算项'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['余额方向'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助核算标志'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['上级科目编码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['是否是标准科目'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['公共会计科目代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['科目类别名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_uuid'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['行政区划代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目级别'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['科目全称'],
              type: 'STRING',
            },
          ],
          primaryKeys: null,
          tableName: '基础表_会计管理数据_公共会计科目表',
        },
        {
          columns: [
            {
              fmt: null,
              foreignKeys: null,
              name: ['期初外币余额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助级别'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目全称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_批次'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['是否最底级科目'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目编码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['上级科目编码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿编号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_uuid'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计月份'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['币种名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['期初余额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['期末余额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目级别'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['分录数'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['贷方外币发生额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['借方发生额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_区划'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['借方外币发生额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['余额方向'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['贷方发生额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['期末外币余额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['行政区划代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助类型'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助编码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['上级辅助编码'],
              type: 'STRING',
            },
          ],
          primaryKeys: null,
          tableName: '基础表_会计管理数据_辅助余额表',
        },
        {
          columns: [
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_批次'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['是否最底级科目'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['科目类别编号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助核算项'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目编码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助核算标志'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['上级科目编码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['是否是标准科目'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿编号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['公共会计科目代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_uuid'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目级别'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['科目全称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['是否现金或现金等价物'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_区划'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['余额方向'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['科目类别名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['行政区划代码'],
              type: 'STRING',
            },
          ],
          primaryKeys: null,
          tableName: '基础表_会计管理数据_会计科目表',
        },
        {
          columns: [
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_区划'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_批次'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['单位性质'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['上级代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['组织机构代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_uuid'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['行政区划代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['单位分类'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['单位类别'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['代码级次'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['是否末级'],
              type: 'STRING',
            },
          ],
          primaryKeys: null,
          tableName: '基础表_会计管理数据_部门信息表',
        },
        {
          columns: [
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['第十级科目长度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['第二级科目长度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['编码分隔符'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_批次'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['第十五级科目长度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['第九级科目长度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目编码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['第十三级科目长度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['第十八级科目长度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['第四级科目长度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿编号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_uuid'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['第十一级科目长度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['第六级科目长度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_区划'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['第十四级科目长度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['第二十级科目长度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['第八级科目长度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['第十七级科目长度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['第十九级科目长度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['第十二级科目长度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['行政区划代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['第三级科目长度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['第五级科目长度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['第一级科目长度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['第十六级科目长度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['第七级科目长度'],
              type: 'STRING',
            },
          ],
          primaryKeys: null,
          tableName: '基础表_会计管理数据_科目设置',
        },
        {
          columns: [
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_区划'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计核算单位'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_批次'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['开发单位'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['单位性质'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['采集类型'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['采集时间'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['行业分类'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿编号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['组织机构代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_uuid'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['版本号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['行政区划代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['本位币'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目结构'],
              type: 'STRING',
            },
          ],
          primaryKeys: null,
          tableName: '基础表_会计管理数据_电子账簿信息表',
        },
        {
          columns: [
            {
              fmt: null,
              foreignKeys: null,
              name: ['凭证类型编号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['数量'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['源凭证号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['审核人'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_批次'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['作废标志'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目编码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['票据类型'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['结算方式'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿编号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['凭证号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_uuid'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['票据号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计月份'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['币种名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['单价'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['附件数'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['对方科目名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['贷方外币发生额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['凭证日期'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['借方发生额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_区划'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['对方科目编码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['票据日期'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['借方外币发生额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['结转标志'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['汇率'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['记账标志'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['贷方发生额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['出纳人'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['记账人'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['行政区划代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['制单人'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['凭证摘要'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['凭证类型名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['财务主管'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['分录序号'],
              type: 'STRING',
            },
          ],
          primaryKeys: null,
          tableName: '基础表_会计管理数据_凭证表',
        },
        {
          columns: [
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_区划'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_批次'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['开始日期'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿编号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_uuid'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['行政区划代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计月份'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['截止日期'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_单位代码'],
              type: 'STRING',
            },
          ],
          primaryKeys: null,
          tableName: '基础表_会计管理数据_会计期间定义',
        },
        {
          columns: [
            {
              fmt: null,
              foreignKeys: null,
              name: ['凭证类型编号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_批次'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目编码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿编号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['凭证号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_uuid'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计月份'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['币种名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['贷方外币发生额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['借方发生额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_区划'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['借方外币发生额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['汇率'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['贷方发生额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['行政区划代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['凭证摘要'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助类型'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['凭证类型名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['分录序号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助编码'],
              type: 'STRING',
            },
          ],
          primaryKeys: null,
          tableName: '基础表_会计管理数据_凭证辅助明细表',
        },
        {
          columns: [
            {
              fmt: null,
              foreignKeys: null,
              name: ['闰年'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计月份'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['截止日期'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['开始日期'],
              type: 'STRING',
            },
          ],
          primaryKeys: null,
          tableName: '_period',
        },
        {
          columns: [
            {
              fmt: null,
              foreignKeys: null,
              name: ['借方发生额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_区划'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_批次'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目编码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['余额方向'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['上级科目编码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['贷方发生额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿编号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_uuid'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['行政区划代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['期初余额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['期末余额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目级别'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['分录数'],
              type: 'STRING',
            },
          ],
          primaryKeys: null,
          tableName: '基础表_会计管理数据_全年科目余额表',
        },
        {
          columns: [
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助级别'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_批次'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['是否最底级科目'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目编码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['币种代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['上级科目编码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿编号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_uuid'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['外币本期贷方发生额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计月份'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['本币期初余额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目级别'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['科目全称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['本币期末余额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['外币期初余额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['本币本期贷方发生额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_区划'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['本币本期借方发生额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['外币本期借方发生额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['余额方向'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['外币期末余额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['行政区划代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['凭证数量'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助类型'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助编码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['上级辅助编码'],
              type: 'STRING',
            },
          ],
          primaryKeys: null,
          tableName: '基础表_会计管理数据_全年辅助余额表',
        },
        {
          columns: [
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_区划'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_批次'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿编号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_uuid'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['行政区划代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助级次'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助类型'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助说明'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助编码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['上级辅助编码'],
              type: 'STRING',
            },
          ],
          primaryKeys: null,
          tableName: '基础表_会计管理数据_辅助信息表',
        },
        {
          columns: [
            {
              fmt: null,
              foreignKeys: null,
              name: ['是否现金或现金等价物'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_区划'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['期初外币余额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_批次'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['是否最底级科目'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目编码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['余额方向'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['上级科目编码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿编号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_uuid'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['行政区划代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['币种名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计月份'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['期初余额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目级别'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['科目全称'],
              type: 'STRING',
            },
          ],
          primaryKeys: null,
          tableName: '基础表_会计管理数据_科目余额期初表',
        },
        {
          columns: [
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_区划'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['期初外币余额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_批次'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['是否最底级科目'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目编码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['余额方向'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['上级科目编码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿编号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_uuid'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['行政区划代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['币种名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计月份'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['期初余额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助类型'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目级别'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['辅助编码'],
              type: 'STRING',
            },
          ],
          primaryKeys: null,
          tableName: '基础表_会计管理数据_辅助余额期初表',
        },
        {
          columns: [
            {
              fmt: null,
              foreignKeys: null,
              name: ['期初外币余额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_批次'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['是否最底级科目'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目编码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['上级科目编码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计电子账簿编号'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_uuid'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计月份'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['币种名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['期初余额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['期末余额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['会计科目级别'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['贷方外币发生额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['科目全称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['是否现金或现金等价物'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['借方发生额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预算单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_区划'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['借方外币发生额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['余额方向'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['贷方发生额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['期末外币余额'],
              type: 'NUMERIC',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['行政区划代码'],
              type: 'STRING',
            },
          ],
          primaryKeys: null,
          tableName: '基础表_会计管理数据_科目余额表',
        },
        {
          columns: [
            {
              fmt: null,
              foreignKeys: null,
              name: ['财政系统单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_区划'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['财务系统单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_批次'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['单位性质'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_年度'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['财政系统单位名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_uuid'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['行政区划代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['财务系统单位名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['上级单位名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预留1'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['etl_单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['备注'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['配置名称'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['单位级次'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['上级单位代码'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['预留'],
              type: 'STRING',
            },
            {
              fmt: null,
              foreignKeys: null,
              name: ['是否末级'],
              type: 'STRING',
            },
          ],
          primaryKeys: null,
          tableName: '基础表_会计管理数据_配置信息表',
        },
      ],
    },
  ],
};
