export const jdDict1 = {
  dictCode: '100000',
  dictName: '车辆用途',
  dictType: 'VD03901',
  parentCode: '-1',
  isLeaf: false,
  children: [
    {
      dictCode: '101000',
      dictName: '部级干部公务用车',
      dictType: 'VD03901',
      parentCode: '100000',
      isLeaf: false,
      children: [
        {
          dictCode: '101001',
          dictName: '离退休副省部级干部用车',
          dictType: 'VD03901',
          parentCode: '101000',
          isLeaf: true,
          children: [],
        },
        {
          dictCode: '101002',
          dictName: '非离退休副省部级干部用车',
          dictType: 'VD03901',
          parentCode: '101000',
          isLeaf: true,
          children: [],
        },
      ],
    },
    {
      dictCode: '103000',
      dictName: '机要通信用车',
      dictType: 'VD03901',
      parentCode: '100000',
      isLeaf: true,
      children: [],
    },
    {
      dictCode: '104000',
      dictName: '应急保障用车',
      dictType: 'VD03901',
      parentCode: '100000',
      isLeaf: true,
      children: [],
    },
    {
      dictCode: '105000',
      dictName: '执法执勤用车',
      dictType: 'VD03901',
      parentCode: '100000',
      isLeaf: true,
      children: [],
    },
    {
      dictCode: '106000',
      dictName: '特种专业技术用车',
      dictType: 'VD03901',
      parentCode: '100000',
      isLeaf: true,
      children: [],
    },
    {
      dictCode: '107000',
      dictName: '离退休干部服务保障用车',
      dictType: 'VD03901',
      parentCode: '100000',
      isLeaf: true,
      children: [],
    },
    {
      dictCode: '108000',
      dictName: '中管干部公务用车',
      dictType: 'VD03901',
      parentCode: '100000',
      isLeaf: true,
      children: [],
    },
    {
      dictCode: '109000',
      dictName: '其他按规定配备的车辆',
      dictType: 'VD03901',
      parentCode: '100000',
      isLeaf: false,
      children: [
        {
          dictCode: '109100',
          dictName: '主要负责人用车',
          dictType: 'VD03901',
          parentCode: '109000',
          isLeaf: true,
          children: [],
        },
        {
          dictCode: '109200',
          dictName: '高层次人才用车',
          dictType: 'VD03901',
          parentCode: '109000',
          isLeaf: true,
          children: [],
        },
        {
          dictCode: '109300',
          dictName: '通勤用车',
          dictType: 'VD03901',
          parentCode: '109000',
          isLeaf: true,
          children: [],
        },
        {
          dictCode: '109400',
          dictName: '其他公务用车',
          dictType: 'VD03901',
          parentCode: '109000',
          isLeaf: true,
          children: [],
        },
      ],
    },
    {
      dictCode: '110000',
      dictName: '业务用车',
      dictType: 'VD03901',
      parentCode: '100000',
      isLeaf: true,
      children: [],
    },
  ],
};
